services:

  reverse-proxy:
    image: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.email=contact@noreply.cfpt.info"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # - "443:443"
      - "8080:80"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./letsencrypt:/letsencrypt"

  web:
    build: .
    env_file: .env
    # depends_on:
    #   db:
    #     condition: service_healthy
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/src
      - ./uploads:/var/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`trainingtpi.localhost`)"
      # - "traefik.http.routers.client.entrypoints=websecure"
      # - "traefik.http.routers.client.tls.certresolver=myresolvr"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  
  db: 
    image: mariadb:12
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: accounts_images_user
      MARIADB_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_DATABASE: accounts_images_db
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/initDb.sql
      - mariadb_data:/var/lib/mysql:Z
    healthcheck:
      test: ["CMD-SHELL", "mysql -u accounts_images_user -p${MARIADB_USER_PASSWORD} -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mariadb_data: