services:
  web:
    build: .
    env_file: .env
    # depends_on:
    #   db:
    #     condition: service_healthy
    depends_on:
      - db
    ports:
      - 8089:80
    volumes:
      - ./src:/var/www/html/src
      - ./uploads:/var/uploads
  
  db: 
    image: mariadb:12
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: accounts_images_user
      MARIADB_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_DATABASE: accounts_images_db
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/initDb.sql
      - mariadb_data:/var/lib/mysql:Z
    healthcheck:
      test: ["CMD-SHELL", "mysql -u accounts_images_user -p${MARIADB_USER_PASSWORD} -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mariadb_data: